// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP2.REST.AccessData;

namespace TP2.REST.AccessData.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20201018004554_CreateBibliotecaDB")]
    partial class CreateBibliotecaDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TP2.REST.Domain.Entities.Alquiler", b =>
                {
                    b.Property<int>("AlquilerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<int>("EstadoID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAlquiler")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("AlquilerId");

                    b.HasIndex("ClienteID");

                    b.HasIndex("EstadoID");

                    b.HasIndex("ISBN");

                    b.ToTable("Alquiler");
                });

            modelBuilder.Entity("TP2.REST.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Apellido = "Gargatagli",
                            DNI = "40394722",
                            Email = "ciroshaila@gmail.com",
                            Nombre = "Ciro"
                        });
                });

            modelBuilder.Entity("TP2.REST.Domain.Entities.EstadoAlquiler", b =>
                {
                    b.Property<int>("EstadoAlquilerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("EstadoAlquilerId");

                    b.ToTable("EstadoAlquiler");

                    b.HasData(
                        new
                        {
                            EstadoAlquilerId = 1,
                            Descripcion = "Reservado"
                        },
                        new
                        {
                            EstadoAlquilerId = 2,
                            Descripcion = "Alquilado"
                        },
                        new
                        {
                            EstadoAlquilerId = 3,
                            Descripcion = "Cancelado"
                        });
                });

            modelBuilder.Entity("TP2.REST.Domain.Entities.Libro", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Edicion")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Editorial")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("varchar(110)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("ISBN");

                    b.ToTable("Libro");

                    b.HasData(
                        new
                        {
                            ISBN = "8478884459",
                            Autor = "J.K. Rowling",
                            Edicion = "1997",
                            Editorial = "Salamandra",
                            Imagen = "https://images.cdn2.buscalibre.com/fit-in/360x360/a2/9e/a29ebbd39810f964999f2a9f5f773af8.jpg",
                            Stock = 10,
                            Titulo = "Harry Potter y la piedra filosofal"
                        },
                        new
                        {
                            ISBN = "6071121639",
                            Autor = "Stephen Chbosky",
                            Edicion = "2013",
                            Editorial = "Alfaguara",
                            Imagen = "https://images-na.ssl-images-amazon.com/images/I/514XOeteoRL._SX319_BO1,204,203,200_.jpg",
                            Stock = 7,
                            Titulo = "Las ventajas de ser invisible"
                        },
                        new
                        {
                            ISBN = "9789876295116",
                            Autor = "Eduardo Galeano",
                            Edicion = "2014",
                            Editorial = "SIGLO XXI EDITORES",
                            Imagen = "https://contentv2.tap-commerce.com/cover/large/9789876295116_1.jpg?id_com=1113",
                            Stock = 9,
                            Titulo = "Las Venas Abiertas De America Latina"
                        },
                        new
                        {
                            ISBN = "9788416709823",
                            Autor = "Joe Padilla",
                            Edicion = "2017",
                            Editorial = "RESERVOIR BOOKS",
                            Imagen = "https://www.isadoralibros.com.uy/sitio/repo/img/9788417125011.jpg",
                            Stock = 15,
                            Titulo = "Ramones"
                        },
                        new
                        {
                            ISBN = "9789872813635",
                            Autor = "Sebastián Duarte",
                            Edicion = "2016",
                            Editorial = "Sebastián Duarte, Sr",
                            Imagen = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTuZGW7GD3BU0e-JZs2CocWnq28bBt3qS8Rtw&usqp=CAU",
                            Stock = 10,
                            Titulo = "Ricky de Flema, El último Punk"
                        },
                        new
                        {
                            ISBN = "9789874109019",
                            Autor = "Roberto Arlt",
                            Edicion = "2016",
                            Editorial = "EDITORIAL BARENHAUS",
                            Imagen = "https://image.isu.pub/181210203225-bdf0823d1bf285c49563674ba22812f3/jpg/page_1.jpg",
                            Stock = 6,
                            Titulo = "El Juguete Rabioso"
                        },
                        new
                        {
                            ISBN = "9788491053538",
                            Autor = "Piotr Kropotkin",
                            Edicion = "2017",
                            Editorial = "PENGUIN CLASICOS",
                            Imagen = "https://images-na.ssl-images-amazon.com/images/I/31XJ19CQG1L._SX311_BO1,204,203,200_.jpg",
                            Stock = 13,
                            Titulo = "La conquista del pan"
                        });
                });

            modelBuilder.Entity("TP2.REST.Domain.Entities.Alquiler", b =>
                {
                    b.HasOne("TP2.REST.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2.REST.Domain.Entities.EstadoAlquiler", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2.REST.Domain.Entities.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
