// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP2.REST.AccessData;

namespace TP2.REST.AccessData.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    partial class BibliotecaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TP2.REST.Domain.Entities.Alquiler", b =>
                {
                    b.Property<int>("AlquilerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<int>("EstadoID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAlquiler")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("AlquilerId");

                    b.HasIndex("ClienteID");

                    b.HasIndex("EstadoID");

                    b.HasIndex("ISBN");

                    b.ToTable("Alquiler");
                });

            modelBuilder.Entity("TP2.REST.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("TP2.REST.Domain.Entities.EstadoAlquiler", b =>
                {
                    b.Property<int>("EstadoAlquilerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("EstadoAlquilerId");

                    b.ToTable("EstadoAlquiler");

                    b.HasData(
                        new
                        {
                            EstadoAlquilerId = 1,
                            Descripcion = "Reservado"
                        },
                        new
                        {
                            EstadoAlquilerId = 2,
                            Descripcion = "Alquilado"
                        },
                        new
                        {
                            EstadoAlquilerId = 3,
                            Descripcion = "Cancelado"
                        });
                });

            modelBuilder.Entity("TP2.REST.Domain.Entities.Libro", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Edicion")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Editorial")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("ISBN");

                    b.ToTable("Libro");

                    b.HasData(
                        new
                        {
                            ISBN = "8478884459",
                            Autor = "J.K. Rowling",
                            Edicion = "1997",
                            Editorial = "Salamandra",
                            Imagen = "",
                            Stock = 10,
                            Titulo = "Harry Potter y la piedra filosofal"
                        },
                        new
                        {
                            ISBN = "6071121639",
                            Autor = "Stephen Chbosky",
                            Edicion = "2013",
                            Editorial = "Alfaguara",
                            Imagen = "",
                            Stock = 7,
                            Titulo = "Las ventajas de ser invisible"
                        },
                        new
                        {
                            ISBN = "9789876295116",
                            Autor = "Eduardo Galeano",
                            Edicion = "2014",
                            Editorial = "SIGLO XXI EDITORES",
                            Imagen = "",
                            Stock = 9,
                            Titulo = "Las Venas Abiertas De America Latina"
                        },
                        new
                        {
                            ISBN = "9788416709823",
                            Autor = "Joe Padilla",
                            Edicion = "2017",
                            Editorial = "RESERVOIR BOOKS",
                            Imagen = "",
                            Stock = 15,
                            Titulo = "Ramones"
                        },
                        new
                        {
                            ISBN = "9789872813635",
                            Autor = "Sebastián Duarte",
                            Edicion = "2016",
                            Editorial = "Sebastián Duarte, Sr",
                            Imagen = "",
                            Stock = 10,
                            Titulo = "Ricky de Flema, El último Punk"
                        },
                        new
                        {
                            ISBN = "9789874109019",
                            Autor = "Roberto Arlt",
                            Edicion = "2016",
                            Editorial = "EDITORIAL BARENHAUS",
                            Imagen = "",
                            Stock = 6,
                            Titulo = "El Juguete Rabioso"
                        },
                        new
                        {
                            ISBN = "9788491053538",
                            Autor = "Piotr Kropotkin",
                            Edicion = "2017",
                            Editorial = "PENGUIN CLASICOS",
                            Imagen = "",
                            Stock = 13,
                            Titulo = "La conquista del pan"
                        });
                });

            modelBuilder.Entity("TP2.REST.Domain.Entities.Alquiler", b =>
                {
                    b.HasOne("TP2.REST.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2.REST.Domain.Entities.EstadoAlquiler", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2.REST.Domain.Entities.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
